name: Test JDKs Downloaded

on:
  push:
    branches:
      - main
  pull_request:


jobs:
  test-download:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Take a JDK that is not supported by the toolchain yet
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'microsoft'

      - name: Run tests
        run: ./gradlew test
